import { StyleSheet } from 'react-native';
import { colors, fonts } from '@/src/theme/theme';

export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.ink },
  emptyContainer: {
    flex: 1,
    backgroundColor: colors.ink,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  emptyLoadText: {
    fontFamily: fonts.uiMedium,
    fontSize: 9,
    letterSpacing: 3,
    color: colors.fog,
  },
  headerCrest: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(196,150,26,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(196,150,26,0.03)',
    marginBottom: 8,
  },
  emptyChat: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 80,
    gap: 10,
  },
  emptyChatTitle: {
    fontFamily: fonts.display,
    fontSize: 22,
    color: colors.parchment,
    marginBottom: 4,
  },
  emptyChatDesc: {
    fontFamily: fonts.body,
    fontSize: 12,
    color: colors.fog,
    textAlign: 'center',
    paddingHorizontal: 32,
  },

  // ── Room Header ──
  roomHeader: {
    paddingTop: 0,
    paddingBottom: 14,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(11,10,8,0.97)',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.ash,
  },
  headerBtn: { padding: 8 },
  headerCenter: { flex: 1, alignItems: 'center' },
  roomTitle: {
    fontFamily: fonts.sub,
    fontSize: 16,
    color: colors.parchment,
    marginBottom: 3,
  },
  roomMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  roomMetaText: {
    fontFamily: fonts.ui,
    fontSize: 9,
    letterSpacing: 0.5,
    color: colors.fog,
  },
  roomMetaDot: {
    width: 2,
    height: 2,
    borderRadius: 1,
    backgroundColor: colors.fog,
    marginHorizontal: 4,
  },
  roomMetaPrivate: {
    fontFamily: fonts.uiMedium,
    fontSize: 8,
    letterSpacing: 1,
    color: colors.sepia,
  },

  // ── Messages ──
  messagesList: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 24,
    gap: 4,
  },
  msgWrapper: { marginBottom: 2 },
  msgSelf: { alignItems: 'flex-end' },
  msgOther: { alignItems: 'flex-start' },
  msgCompact: { marginTop: -2 },
  msgAvatar: {
    position: 'absolute',
    left: -4,
    top: 4,
    width: 28,
    height: 28,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: colors.soot,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.ash,
  },
  msgAvatarImg: { width: '100%', height: '100%' },
  msgAvatarLetter: {
    fontFamily: fonts.display,
    color: colors.fog,
    fontSize: 13,
  },
  msgContentCol: { maxWidth: '82%', paddingLeft: 32 },
  msgContentColSelf: { alignItems: 'flex-end', paddingLeft: 0 },
  msgHeader: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
    marginBottom: 4,
  },
  msgHeaderSelf: { justifyContent: 'flex-end' },
  msgAuthor: {
    fontFamily: fonts.uiMedium,
    fontSize: 10,
    letterSpacing: 0.5,
    color: colors.bone,
  },
  msgTime: {
    fontFamily: fonts.ui,
    fontSize: 9,
    color: colors.fog,
    opacity: 0.5,
  },

  msgBubble: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
  },
  msgBubbleSelf: {
    backgroundColor: 'rgba(196,150,26,0.08)',
    borderBottomRightRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(196,150,26,0.25)',
  },
  msgBubbleOther: {
    backgroundColor: colors.soot,
    borderBottomLeftRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.ash,
  },
  msgText: {
    fontFamily: fonts.body,
    fontSize: 14,
    color: colors.parchment,
    lineHeight: 22,
  },

  // ── Reply Quote ──
  replyQuote: {
    backgroundColor: 'rgba(0,0,0,0.3)',
    padding: 8,
    borderRadius: 4,
    marginBottom: 8,
    borderLeftWidth: 2,
    borderLeftColor: colors.sepia,
  },
  replyQuoteHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 3,
  },
  replyQuoteAuthor: {
    fontFamily: fonts.uiMedium,
    fontSize: 9,
    letterSpacing: 0.5,
    color: colors.sepia,
  },
  replyQuoteContent: {
    fontFamily: fonts.bodyItalic,
    fontSize: 12,
    color: colors.fog,
    lineHeight: 17,
  },

  // ── Shared Film Card ──
  sharedCard: {
    flexDirection: 'row',
    backgroundColor: 'rgba(0,0,0,0.4)',
    borderRadius: 4,
    overflow: 'hidden',
    marginTop: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.ash,
  },
  sharedPoster: { width: 48, height: 72 },
  sharedInfo: {
    padding: 10,
    flex: 1,
    justifyContent: 'center',
  },
  sharedTypeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 4,
  },
  sharedTypeText: {
    fontFamily: fonts.uiMedium,
    fontSize: 8,
    letterSpacing: 1.5,
    color: colors.sepia,
  },
  sharedTitle: {
    fontFamily: fonts.sub,
    fontSize: 13,
    color: colors.bone,
    lineHeight: 17,
  },

  // ── Input ──
  inputWrapper: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: colors.ink,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.ash,
  },
  replyBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.soot,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 4,
    marginBottom: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.ash,
    gap: 8,
  },
  replyBannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  replyBannerAuthor: {
    fontFamily: fonts.uiMedium,
    fontSize: 10,
    color: colors.sepia,
    letterSpacing: 0.5,
  },
  replyBannerText: {
    flex: 1,
    fontFamily: fonts.body,
    fontSize: 12,
    color: colors.fog,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
  },
  chatInput: {
    flex: 1,
    minHeight: 40,
    maxHeight: 120,
    backgroundColor: colors.soot,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 12,
    color: colors.bone,
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 18,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.ash,
  },
  sendBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.sepia,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.sepia,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  sendBtnDisabled: {
    backgroundColor: colors.ash,
    shadowOpacity: 0,
  },

  // ── Preview Banner ──
  previewBanner: {
    paddingHorizontal: 16,
    paddingTop: 16,
    backgroundColor: 'rgba(11,10,8,0.97)',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.ash,
    alignItems: 'center',
    gap: 12,
  },
  previewBannerText: {
    fontFamily: fonts.ui,
    fontSize: 11,
    color: colors.fog,
    letterSpacing: 0.5,
  },
  previewBtn: {
    backgroundColor: colors.sepia,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 4,
    width: '100%',
    alignItems: 'center',
  },
  previewBtnDisabled: {
    opacity: 0.5,
  },
  previewBtnText: {
    fontFamily: fonts.uiMedium,
    fontSize: 11,
    letterSpacing: 2,
    color: colors.ink,
  },

  // ── Action Sheet ──
  actionBackdrop: { flex: 1 },
  actionSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.ink,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 24,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: 'rgba(196,150,26,0.15)',
  },
  actionHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.08)',
    alignSelf: 'center',
    marginBottom: 20,
  },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    gap: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.soot,
  },
  actionBtnLast: { borderBottomWidth: 0 },
  actionBtnText: {
    fontFamily: fonts.uiMedium,
    fontSize: 12,
    letterSpacing: 2,
    color: colors.parchment,
  },
  actionBtnDanger: { color: colors.bloodReel },

  // ── Settings Sheet ──
  settingsSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '85%',
    backgroundColor: colors.ink,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 24,
    paddingBottom: 28,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: 'rgba(196,150,26,0.15)',
  },
  settingsHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  settingsTitle: {
    fontFamily: fonts.display,
    fontSize: 22,
    color: colors.parchment,
  },
  settingsListHeader: { gap: 20, marginBottom: 16 },
  settingsSection: { gap: 8 },
  settingsLabel: {
    fontFamily: fonts.uiMedium,
    fontSize: 9,
    letterSpacing: 2,
    color: colors.fog,
  },
  inviteCodeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 14,
    backgroundColor: 'rgba(196,150,26,0.06)',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(196,150,26,0.3)',
    borderStyle: 'dashed',
    gap: 12,
  },
  inviteCodeText: {
    fontFamily: fonts.uiBold,
    fontSize: 18,
    letterSpacing: 6,
    color: colors.parchment,
  },

  // ── Members ──
  memberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.soot,
  },
  memberAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.soot,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.ash,
  },
  memberAvatarImg: { width: '100%', height: '100%' },
  memberAvatarLetter: {
    fontFamily: fonts.display,
    fontSize: 14,
  },
  memberName: {
    flex: 1,
    fontFamily: fonts.uiMedium,
    fontSize: 12,
    letterSpacing: 1,
    color: colors.bone,
  },
  memberBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 2,
    backgroundColor: 'rgba(196,150,26,0.08)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(196,150,26,0.2)',
  },
  memberBadgeText: {
    fontFamily: fonts.uiMedium,
    fontSize: 8,
    letterSpacing: 1.5,
    color: colors.sepia,
  },
  settingsFooter: {
    marginTop: 32,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.ash,
    paddingTop: 20,
  },
  leaveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 14,
    gap: 10,
  },
  leaveBtnText: {
    fontFamily: fonts.uiMedium,
    fontSize: 10,
    letterSpacing: 2,
    color: colors.sepia,
  },
});




