import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // Generated build output and non-source directories — not part of the app, never linted.
  globalIgnores([
    'dist',
    '.vercel',          // Vercel build output
    '.gemini',          // unrelated tooling assets
    'scripts/archive',  // archived one-off scripts
    'mobile',           // the mobile app has its own eslint config
    'public/sw.js',     // service worker (generated by vite-plugin-pwa)
    'migrate-logger.js',
  ]),
  {
    files: ['**/*.{js,jsx}'],
    extends: [
      js.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
      parserOptions: {
        ecmaVersion: 'latest',
        ecmaFeatures: { jsx: true },
        sourceType: 'module',
      },
    },
    rules: {
      'no-unused-vars': ['error', { varsIgnorePattern: '^[A-Z_]' }],
    },
  },
  // Node-runtime files: serverless functions, build/ops scripts, and config files.
  {
    files: ['api/**/*.js', 'scripts/**/*.js', '*.config.js'],
    languageOptions: {
      globals: { ...globals.node },
    },
  },
])
