import { colors } from '@/src/theme/theme';

// ── Tier Data (matches web MembershipPage.tsx exactly) ──
export const TIERS = [
  {
    id: 'cinephile',
    name: 'The\nCinephile',
    label: 'BASIC ACCESS',
    labelColor: colors.fog,
    price: 'Free',
    pricePeriod: 'FOREVER',
    billing: null,
    priceMonthly: null,
    priceAnnual: null,
    annualEquiv: null,
    borderColor: 'rgba(184,137,26,0.08)',
    bgGradient: ['rgba(22,18,12,0.98)', 'rgba(10,7,3,0.98)'] as const,
    accentColor: colors.fog,
    dotColor: colors.fog,
    includes: null,
    featuredFeature: null,
    features: ['Log & Rate Films', 'The Diary & Watchlist', 'Basic Profile', 'Unlimited Custom Lists', 'Import & Export Archive'],
    cta: 'JOIN FREE',
    ctaStyle: 'ghost' as const,
  },
  {
    id: 'archivist',
    name: 'The\nArchivist',
    label: 'PREMIUM TOOLS',
    labelColor: colors.sepia,
    price: '1.99',
    pricePeriod: '/ MO',
    billing: 'BILLED ANNUALLY ($19.99/YR)',
    // Billing-choice statics (fallbacks when live store pricing is unavailable).
    priceMonthly: '1.99',
    priceAnnual: '19.99',
    annualEquiv: '1.67',
    borderColor: 'rgba(184,137,26,0.35)',
    bgGradient: ['rgba(30,24,14,0.98)', 'rgba(10,7,3,0.98)'] as const,
    accentColor: colors.sepia,
    dotColor: colors.sepia,
    popular: true,
    includes: 'Everything in Free, plus:',
    featuredFeature: {
      title: 'The Editorial\nDesk',
      desc: 'Pro-level review formatting. Inject movie stills, pull-quotes, and drop caps into your logs.',
    },
    features: [
      'The Physical Archive\n(Track 4K/Blu-Ray/VHS)',
      'The Vault (Private Notes)',
      'The Gilded Frame\n(Exclusive Animated Gold Borders)',
      'The Lounge\n(Exclusive Cinema Chat Rooms)',
    ],
    cta: 'BECOME AN ARCHIVIST',
    ctaStyle: 'primary' as const,
  },
  {
    id: 'auteur',
    name: 'The Auteur',
    label: 'ULTIMATE PATRONAGE',
    // One ruby family — the legible crimson token, not a fourth stray red.
    labelColor: colors.crimson,
    price: '4.99',
    pricePeriod: '/ MO',
    billing: 'BILLED ANNUALLY ($49.99/YR)',
    // Billing-choice statics (fallbacks when live store pricing is unavailable).
    priceMonthly: '4.99',
    priceAnnual: '49.99',
    annualEquiv: '4.17',
    borderColor: colors.crimsonBorder,
    bgGradient: ['rgba(30,12,12,0.98)', 'rgba(10,7,3,0.98)'] as const,
    accentColor: colors.crimson,
    dotColor: colors.crimson,
    includes: 'Everything in Archivist, plus:',
    featuredFeature: {
      title: 'The Breakdown\nEngine',
      desc: 'Break down films across 6 specific axes \u2014 Story, Script, Acting, Cinematography, Editing & Sound.',
    },
    features: [
      'Publish Essays to The\nDispatch',
      'Curatorial Control\n(Select Alternative TMDB\nPosters)',
      'Poster Glow Profile\nAesthetics',
      'Gold Foil "Auteur" Badge',
      'Early Access to New\nFeatures',
    ],
    cta: 'BECOME AN AUTEUR',
    ctaStyle: 'auteur' as const,
  },
];
