import { StyleSheet } from 'react-native';
import { colors, fonts, effects } from '@/src/theme/theme';

export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.ink },

  // ── Ornamental ──
  ornRule: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginVertical: 14,
  },
  ornLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.sepia,
    opacity: 0.3,
  },

  // ── Crest ──
  crestGlow: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(196,150,26,0.08)',
  },
  crestGlowInner: {
    flex: 1,
    borderRadius: 50,
    backgroundColor: 'rgba(196,150,26,0.04)',
  },

  // ── Gate ──
  gateContainer: {
    flex: 1,
    backgroundColor: colors.ink,
    justifyContent: 'center',
    paddingHorizontal: 36,
  },
  gateCard: {
    alignItems: 'center',
  },
  gateCrestWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 28,
  },
  gateCrest: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 1,
    borderColor: 'rgba(196,150,26,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(196,150,26,0.03)',
  },
  gateTitle: {
    fontFamily: fonts.display,
    fontSize: 24,
    color: colors.parchment,
    marginBottom: 6,
  },
  gateEst: {
    fontFamily: fonts.uiMedium,
    fontSize: 8,
    letterSpacing: 6,
    color: colors.sepia,
    marginBottom: 4,
    opacity: 0.7,
  },
  gateSub: {
    fontFamily: fonts.uiMedium,
    fontSize: 8, // to 8
    letterSpacing: 3,
    color: colors.sepia,
    marginBottom: 20,
  },
  gateDesc: {
    fontFamily: fonts.body,
    fontSize: 11,
    color: colors.bone,
    lineHeight: 18,
    textAlign: 'center',
    marginBottom: 32,
    opacity: 0.8,
  },
  gateCta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.sepia,
    paddingVertical: 15,
    paddingHorizontal: 36,
    borderRadius: 2,
    marginBottom: 28,
  },
  gateCtaText: {
    fontFamily: fonts.uiBold,
    fontSize: 9,
    letterSpacing: 2.5,
    color: colors.ink,
  },
  gateFootnote: {
    fontFamily: fonts.uiMedium,
    fontSize: 7,
    letterSpacing: 3,
    color: colors.fog,
    opacity: 0.4,
    textAlign: 'center',
  },

  // ── Header ──
  header: {
    paddingHorizontal: 20,
    paddingBottom: 18,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.ash,
    alignItems: 'center',
  },
  headerCrestRow: {
    marginBottom: 10,
  },
  headerCrest: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(196,150,26,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(196,150,26,0.03)',
  },
  headerTitle: {
    fontFamily: fonts.display,
    fontSize: 24,
    color: colors.parchment,
    textAlign: 'center',
    lineHeight: 28,
  },
  headerEst: {
    fontFamily: fonts.uiMedium,
    fontSize: 7,
    letterSpacing: 6,
    color: colors.sepia,
    opacity: 0.6,
    marginTop: 2,
    marginBottom: 4,
    textAlign: 'center',
  },
  headerSubtitle: {
    fontFamily: fonts.bodyItalic,
    fontSize: 10,
    color: colors.bone,
    opacity: 0.6,
    textAlign: 'center',
    marginBottom: 10,
  },
  headerOrnRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
    alignSelf: 'stretch',
  },
  headerOrnLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.ash,
  },
  headerExclusive: {
    fontFamily: fonts.uiMedium,
    fontSize: 7,
    letterSpacing: 4,
    color: colors.sepia,
    opacity: 0.6,
  },

  // ── Search ──
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: 'rgba(5,4,3,0.95)',
    borderRadius: 2,
    paddingHorizontal: 14,
    height: 46,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: 'rgba(139,105,20,0.3)',
    gap: 10,
  },
  searchInput: {
    flex: 1,
    fontFamily: fonts.mono,
    fontWeight: '700',
    fontSize: 10,
    color: colors.parchment,
    letterSpacing: 2,
  },

  // ── Actions ──
  actionsRow: {
    flexDirection: 'row',
    marginTop: 12,
    gap: 8,
    alignSelf: 'stretch',
  },
  btnPrimary: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    backgroundColor: colors.sepia,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: colors.sepia,
    height: 46,
    ...effects.shadowSurface,
  },
  btnPrimaryText: {
    fontFamily: fonts.mono,
    fontWeight: '700',
    fontSize: 10,
    letterSpacing: 2.5,
    color: colors.ink,
  },
  inviteWrap: {
    flexDirection: 'row',
    flex: 1,
    gap: 6,
  },
  inviteInput: {
    flex: 1,
    backgroundColor: 'rgba(5,4,3,0.95)',
    borderRadius: 2,
    height: 46,
    paddingHorizontal: 12,
    fontFamily: fonts.mono,
    fontWeight: '700',
    fontSize: 10,
    color: colors.parchment,
    textAlign: 'center',
    letterSpacing: 6,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: 'rgba(139,105,20,0.3)',
  },
  btnJoin: {
    backgroundColor: colors.ash,
    paddingHorizontal: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 2,
    height: 46,
    ...effects.shadowSurface,
  },
  btnJoinDisabled: { opacity: 0.35 },
  btnJoinText: {
    fontFamily: fonts.mono,
    fontWeight: '700',
    fontSize: 10,
    letterSpacing: 2.5,
    color: colors.parchment,
  },

  // ── Scroll ──
  scrollView: { flex: 1 },
  scrollContent: {
    paddingTop: 28,
    paddingBottom: 120,
  },

  // ── Loading ──
  loadingWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    gap: 14,
  },
  loadingText: {
    fontFamily: fonts.uiMedium,
    fontSize: 8,
    letterSpacing: 4,
    color: colors.fog,
  },

  // ── Sections ──
  section: {
    marginBottom: 36,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    gap: 12,
    marginBottom: 6,
  },
  sectionTitleLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.ash,
  },
  sectionLabel: {
    fontFamily: fonts.uiMedium,
    fontSize: 7,
    letterSpacing: 3,
    color: colors.fog,
  },
  sectionSubtext: {
    fontFamily: fonts.bodyItalic,
    fontSize: 9,
    color: colors.fog,
    opacity: 0.5,
    paddingHorizontal: 20,
    marginBottom: 16,
    textAlign: 'center',
  },

  // ── Joined Cards ──
  joinedStrip: {
    gap: 16,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 24,
  },
  joinedCard: {
    width: '42%',
    borderRadius: 2,
    overflow: 'hidden',
    backgroundColor: colors.soot,
    borderWidth: 1.5,
    borderColor: 'rgba(139,105,20,0.3)',
    ...effects.shadowSurface,
    elevation: 8,
  },
  joinedImgWrap: {
    width: '42%',
    aspectRatio: 1 / 1.35,
    overflow: 'hidden',
    position: 'relative',
  },
  joinedImg: {
    width: '100%',
    height: '100%',
  },
  joinedImgPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  joinedGradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '75%',
  },
  unreadDot: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.bloodReel,
    borderWidth: 2,
    borderColor: colors.ink,
    zIndex: 10,
  },
  joinedNameOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 12,
    paddingBottom: 14,
    paddingTop: 4,
  },
  liveIndicator: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.bloodReel,
    marginRight: 6,
  },
  joinedNameText: {
    fontFamily: fonts.mono,
    fontWeight: '700',
    letterSpacing: 1,
    fontSize: 14,
    color: colors.parchment,
    marginBottom: 8,
    lineHeight: 18,
  },
  joinedMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  joinedMetaText: {
    fontFamily: fonts.mono,
    fontWeight: '700',
    fontSize: 9,
    letterSpacing: 2,
    color: colors.fog,
  },
  joinedMetaLine: {
    height: 10,
    width: 1.5,
    backgroundColor: colors.ash,
  },

  // ── Public Cards ──
  publicList: {
    paddingHorizontal: 20,
    gap: 24,
  },
  publicCard: {
    padding: 24, paddingLeft: 28,
    backgroundColor: 'rgba(12,9,7,0.85)',
    borderWidth: 1.5, borderColor: 'rgba(139,105,20,0.3)', borderStyle: 'dashed',
    borderRadius: 4, position: 'relative',
    overflow: 'hidden',
    ...effects.shadowSurface,
  },
  publicAccentBar: {
    position: 'absolute', left: 0, top: 0, bottom: 0, width: 4,
    backgroundColor: colors.sepia, zIndex: 2,
  },
  publicImgTop: {
    width: '100%',
    height: 120,
    marginBottom: 20,
    borderRadius: 2,
    overflow: 'hidden',
    borderColor: 'rgba(139,105,20,0.2)',
    borderWidth: 1.5,
  },
  publicImgContent: { width: '100%', height: '100%' },
  publicBody: { flex: 1 },
  publicName: {
    fontFamily: fonts.display,
    fontSize: 22,
    color: colors.parchment,
    marginBottom: 10,
    lineHeight: 26,
  },
  publicDesc: {
    fontFamily: fonts.mono,
    fontSize: 11,
    color: colors.bone,
    lineHeight: 20,
    marginBottom: 24,
    opacity: 0.8,
  },
  publicPrivateBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: 'rgba(196,150,26,0.04)',
    borderRadius: 2,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: 'rgba(196,150,26,0.3)',
    borderStyle: 'dashed',
  },
  publicPrivateText: {
    fontFamily: fonts.mono,
    fontWeight: '700',
    fontSize: 8,
    letterSpacing: 2.5,
    color: colors.sepia,
  },
  publicFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: 'rgba(139,105,20,0.15)',
    paddingTop: 16,
    marginTop: 8,
  },
  publicMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  publicMetaText: {
    fontFamily: fonts.mono,
    fontWeight: '700',
    fontSize: 9,
    letterSpacing: 2.5,
    color: colors.fog,
  },
  publicEnterTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  publicEnterText: {
    fontFamily: fonts.mono,
    fontWeight: '700',
    fontSize: 9,
    letterSpacing: 2.5,
    color: colors.sepia,
  },

  // ── Empty States ──
  emptyHero: {
    alignItems: 'center',
    paddingHorizontal: 44,
    paddingVertical: 52,
    marginBottom: 8,
  },
  emptyCrestWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(196,150,26,0.2)',
    backgroundColor: 'rgba(196,150,26,0.03)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  emptyTitle: {
    fontFamily: fonts.display,
    fontSize: 15,
    color: colors.parchment,
    textAlign: 'center',
  },
  emptyDesc: {
    fontFamily: fonts.body,
    fontSize: 10,
    color: colors.fog,
    lineHeight: 16,
    textAlign: 'center',
    opacity: 0.7,
  },
  emptyPublic: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 44,
    paddingHorizontal: 24,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.ash,
    borderRadius: 4,
    gap: 8,
  },
  emptyPublicText: {
    fontFamily: fonts.bodyItalic,
    fontSize: 10,
    color: colors.fog,
  },
  emptyPublicHint: {
    fontFamily: fonts.ui,
    fontSize: 9,
    color: colors.fog,
    opacity: 0.5,
    letterSpacing: 1,
  },

  // ── Create Sheet ──
  sheetKeyboard: { flex: 1 },
  sheetBackdrop: { flex: 1 },
  sheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(7,5,4,0.98)',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    padding: 24,
    borderWidth: 1.5,
    borderBottomWidth: 0,
    borderColor: 'rgba(139,105,20,0.3)',
    ...effects.shadowSurface,
    elevation: 20,
  },
  sheetHandle: {
    width: 48,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(139,105,20,0.2)',
    alignSelf: 'center',
    marginBottom: 24,
  },
  sheetHeaderWrap: { marginBottom: 28 },
  sheetEyebrow: {
    fontFamily: fonts.mono,
    fontWeight: '700',
    fontSize: 8,
    letterSpacing: 4,
    color: colors.fog,
    marginBottom: 8,
  },
  sheetTitle: {
    fontFamily: fonts.display,
    fontSize: 24,
    color: colors.parchment,
    letterSpacing: 1,
  },
  field: { marginBottom: 22 },
  fieldLabel: {
    fontFamily: fonts.mono,
    fontWeight: '700',
    fontSize: 9,
    letterSpacing: 3,
    color: colors.sepia,
    marginBottom: 8,
  },
  fieldInput: {
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'rgba(139,105,20,0.3)',
    backgroundColor: 'rgba(255,255,255,0.02)',
    paddingHorizontal: 16,
    paddingVertical: 16,
    fontFamily: fonts.mono,
    fontWeight: '700',
    fontSize: 14,
    color: colors.parchment,
    borderRadius: 2,
  },
  fieldTextarea: {
    height: 80,
    textAlignVertical: 'top',
  },
  fieldCharCount: {
    fontFamily: fonts.ui,
    fontSize: 8,
    color: colors.fog,
    opacity: 0.3,
    textAlign: 'right',
    marginTop: 4,
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 28,
  },
  toggleInfo: { flex: 1, marginRight: 16 },
  toggleLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  toggleLabel: {
    fontFamily: fonts.uiMedium,
    fontSize: 10,
    letterSpacing: 1,
    color: colors.parchment,
  },
  toggleDesc: {
    fontFamily: fonts.bodyItalic,
    fontSize: 11,
    color: colors.fog,
  },
  sheetActions: {
    flexDirection: 'row',
    gap: 12,
  },
  sheetBtnGhost: {
    flex: 1,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 2,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: 'rgba(139,105,20,0.3)',
  },
  sheetBtnGhostText: {
    fontFamily: fonts.mono,
    fontWeight: '700',
    fontSize: 10,
    letterSpacing: 3,
    color: colors.parchment,
  },
  sheetBtnPrimary: {
    flex: 1,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 2,
    backgroundColor: colors.sepia,
    ...effects.shadowSurface,
  },
  sheetBtnPrimaryText: {
    fontFamily: fonts.mono,
    fontWeight: '700',
    fontSize: 10,
    letterSpacing: 3,
    color: colors.ink,
  },
  sheetBtnDisabled: { opacity: 0.35 },
});
