/**
 * ADVANCES — how wide each character of a face is, measured from the app's own
 * font file, written as a table the app can do arithmetic with.
 *
 *   node mockups/tools/advances.cjs
 *
 * Writes src/theme/ryeAdvances.ts: the advance of every character a profile
 * name can be set in (they are set in capitals), in ems. The profile uses it to
 * choose the largest size at which a member's longest WORD fits the column —
 * a word cannot wrap, and a character count cannot tell a W from an I.
 */
const fs = require('fs');
const path = require('path');
const { chromium, fonts, MOBILE } = require('./harness.cjs');

// Capitals, digits, the punctuation a name or handle carries, and Latin-1
// capitals (É, Ø…) — what `.toUpperCase()` leaves in a Western name.
const CHARS = [
  ...'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
  ...' _-.\',&!?@#()/:;"+*',
  ...Array.from({ length: 0xde - 0xc0 + 1 }, (_, i) => String.fromCharCode(0xc0 + i)).filter((c) => c !== '×'),
];

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.setContent(`<!doctype html><html><head><style>${fonts()}</style></head><body><span style="font-family:Rye">A</span></body></html>`);
  await page.evaluate(() => document.fonts.ready);
  const table = await page.evaluate((chars) => {
    const c = document.createElement('canvas').getContext('2d');
    c.font = '1000px Rye';
    const out = {};
    for (const ch of chars) out[ch] = Math.round(c.measureText(ch).width) / 1000;
    return out;
  }, CHARS);
  await browser.close();

  const widest = Math.max(...Object.values(table));
  const body = Object.entries(table).map(([ch, w]) => `  ${JSON.stringify(ch)}: ${w},`).join('\n');
  const out = `/**
 * Rye's advance widths, in ems, for the characters a profile name is set in.
 * GENERATED by mockups/tools/advances.cjs from the app's own font file — do not
 * edit by hand; re-run the tool if the face changes.
 */
export const RYE_ADVANCE: Readonly<Record<string, number>> = {
${body}
};

/** For a character not in the table (a script Rye does not draw): the widest. */
export const RYE_WIDEST = ${widest};
`;
  const file = path.join(MOBILE, 'src', 'theme', 'ryeAdvances.ts');
  fs.writeFileSync(file, out);
  console.log(`wrote ${path.relative(MOBILE, file)}: ${CHARS.length} characters, widest ${widest}em`);
})();
