-- Generated by scripts/schema-snapshot.mjs
-- Run FIRST: live-extensions.sql, then live-schema.sql, then live-outside-public.sql.
-- Do not edit by hand. Re-run the script after a migration and commit the result.

-- ── extensions
CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA pg_catalog VERSION '1.6.4';
CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA public VERSION '0.20.0';
CREATE EXTENSION IF NOT EXISTS pg_stat_statements WITH SCHEMA extensions VERSION '1.11';
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions VERSION '1.3';
CREATE EXTENSION IF NOT EXISTS supabase_vault WITH SCHEMA vault VERSION '0.3.1';
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions VERSION '1.1';
