-- Generated by scripts/schema-snapshot.mjs
-- Run LAST, after live-schema.sql.
-- Do not edit by hand. Re-run the script after a migration and commit the result.

-- ── triggers this app put on tables outside public
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
CREATE TRIGGER on_auth_user_deleted BEFORE DELETE ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_user_deletion();

-- ── event triggers
CREATE EVENT TRIGGER ensure_rls ON ddl_command_end WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO') EXECUTE FUNCTION public.rls_auto_enable();

-- ── tables whose changes are published (live updates)
ALTER PUBLICATION supabase_realtime ADD TABLE public.dispatch_dossiers_legacy;
ALTER PUBLICATION supabase_realtime ADD TABLE public.log_comments;
ALTER PUBLICATION supabase_realtime ADD TABLE public.lounge_members;
ALTER PUBLICATION supabase_realtime ADD TABLE public.lounge_message_reactions;
ALTER PUBLICATION supabase_realtime ADD TABLE public.lounge_messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;

-- ── storage buckets
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types, avif_autodetection) VALUES ('avatars', 'avatars', 't', 2097152, '{image/jpeg,image/png,image/webp,image/gif}'::text[], 'f');

-- ── row-level security on tables outside public
CREATE POLICY "Avatar images are publicly accessible." ON storage.objects AS PERMISSIVE FOR SELECT TO public USING ((bucket_id = 'avatars'::text));
CREATE POLICY "Users can delete their own avatar." ON storage.objects AS PERMISSIVE FOR DELETE TO public USING (((bucket_id = 'avatars'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));
CREATE POLICY "Users can update mathematically verified images" ON storage.objects AS PERMISSIVE FOR UPDATE TO authenticated USING (((bucket_id = 'avatars'::text) AND ((auth.uid())::text = (storage.foldername(name))[1]))) WITH CHECK (((bucket_id = 'avatars'::text) AND ((auth.uid())::text = (storage.foldername(name))[1]) AND (name ~* '\.(png|jpg|jpeg|webp)$'::text)));
CREATE POLICY "Users can update their own avatar." ON storage.objects AS PERMISSIVE FOR UPDATE TO public USING (((bucket_id = 'avatars'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));
CREATE POLICY "Users can upload mathematically verified images" ON storage.objects AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (((bucket_id = 'avatars'::text) AND ((auth.uid())::text = (storage.foldername(name))[1]) AND (name ~* '\.(png|jpg|jpeg|webp)$'::text)));
CREATE POLICY "Users can upload their own avatar." ON storage.objects AS PERMISSIVE FOR INSERT TO public WITH CHECK (((bucket_id = 'avatars'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));
CREATE POLICY auth_upload ON storage.objects AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (((bucket_id = 'screening-room'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));
CREATE POLICY owner_delete ON storage.objects AS PERMISSIVE FOR DELETE TO authenticated USING (((bucket_id = 'screening-room'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));
CREATE POLICY public_read ON storage.objects AS PERMISSIVE FOR SELECT TO public USING ((bucket_id = 'screening-room'::text));

-- ── scheduled jobs
SELECT cron.schedule_in_database('freeze-closed-ballots', '*/5 * * * *', 'SELECT public.freeze_closed_ballots();', 'postgres', 'postgres', 't');

-- ── vault secrets — names only; a stand-in must be made wherever this is built
-- notify_push_secret

-- ── migration ledger
-- supabase_migrations.schema_migrations rows: 0
