#!/usr/bin/env node
/**
 * lucide-icons.js — writes src/generated/lucideIcons.js: the icons the app
 * imports from lucide-react-native, and only those.
 *
 * Metro has no tree shaking, so `import { X } from 'lucide-react-native'`
 * bundles all 1,700 icons (1.2 MB of the app's 10 MB). metro.config.js sends
 * the app's lucide imports to the generated file instead, which points at each
 * used icon's own module.
 *
 *   npm run icons          rewrite the file
 *   npm run icons -- --check   exit 1 if the file is not what the source asks for
 *
 * lucideIconsAreBundled.guard.test.ts runs the check, so an icon added without
 * rewriting the file fails the suite rather than drawing nothing on a phone.
 */
const fs = require('fs');
const path = require('path');
const ts = require('typescript');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'src', 'generated', 'lucideIcons.js');
const PKG = path.join(ROOT, 'node_modules', 'lucide-react-native', 'dist', 'esm');

/** Every name the package exports, and the icon module it comes from. */
function packageNames() {
  const barrel = fs.readFileSync(path.join(PKG, 'lucide-react-native.js'), 'utf8');
  const names = new Map();
  const line = /^export \{ ([^}]+) \} from '\.\/icons\/([a-z0-9-]+)\.js';$/gm;
  for (let m; (m = line.exec(barrel)); ) {
    for (const part of m[1].split(',')) {
      const as = part.trim().match(/^default as (\w+)$/);
      if (as) names.set(as[1], m[2]);
    }
  }
  return names;
}

/** The value names the app's source imports from lucide-react-native. */
function usedNames() {
  const used = new Set();
  const walk = (dir) => {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      if (e.name === 'node_modules' || e.name === '__tests__' || e.name === 'generated' || e.name.startsWith('.')) continue;
      const p = path.join(dir, e.name);
      if (e.isDirectory()) { walk(p); continue; }
      if (!/\.(tsx?|jsx?)$/.test(e.name) || /\.test\./.test(e.name)) continue;
      const src = fs.readFileSync(p, 'utf8');
      if (!src.includes('lucide-react-native')) continue;
      const sf = ts.createSourceFile(p, src, ts.ScriptTarget.Latest, false, ts.ScriptKind.TSX);
      for (const st of sf.statements) {
        if (!ts.isImportDeclaration(st) || st.moduleSpecifier.text !== 'lucide-react-native') continue;
        const clause = st.importClause;
        if (!clause || clause.isTypeOnly) continue;
        if (clause.name || (clause.namedBindings && !ts.isNamedImports(clause.namedBindings))) {
          throw new Error(`${path.relative(ROOT, p)}: only named icon imports can be bundled one by one`);
        }
        for (const el of clause.namedBindings ? clause.namedBindings.elements : []) {
          if (el.isTypeOnly) continue;
          used.add((el.propertyName || el.name).text);
        }
      }
    }
  };
  walk(path.join(ROOT, 'app'));
  walk(path.join(ROOT, 'src'));
  return used;
}

function render() {
  const names = packageNames();
  const used = [...usedNames()].sort();
  // Types the package exports as values in .d.ts only (LucideIcon, LucideProps) never reach here:
  // a type import is skipped above. Anything else unknown is an error, not a silent undefined.
  const unknown = used.filter((n) => !names.has(n));
  if (unknown.length) throw new Error(`not lucide icons: ${unknown.join(', ')}`);
  const rel = path.relative(path.dirname(OUT), PKG).split(path.sep).join('/');
  const lines = used.map((n) => `export { default as ${n} } from '${rel}/icons/${names.get(n)}.js';`);
  return [
    '// GENERATED by scripts/lucide-icons.js (npm run icons). Do not edit.',
    '// The icons the app imports; metro.config.js sends lucide-react-native here.',
    ...lines,
    '',
  ].join('\n');
}

module.exports = { render, OUT };

if (require.main === module) {
  const want = render();
  const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8').split('\r\n').join('\n') : null;
  if (process.argv.includes('--check')) {
    if (have !== want) { console.error('src/generated/lucideIcons.js is stale: run npm run icons'); process.exit(1); }
    console.log('lucide icons: up to date');
  } else {
    fs.mkdirSync(path.dirname(OUT), { recursive: true });
    fs.writeFileSync(OUT, want);
    console.log(`lucide icons: ${want.split('\n').length - 3} written`);
  }
}
