import { StyleSheet } from 'react-native';
import { colors, fonts, effects } from '@/src/theme/theme';

export const st = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.ink },
  ambientGlow: { position: 'absolute', top: 0, left: 0, right: 0, height: 350, zIndex: 0 },
  navBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: 'rgba(184,137,26,0.1)', zIndex: 10, backgroundColor: 'rgba(5,3,1,0.85)' },
  navBackBtn: { padding: 4 },
  navSaveText: { fontFamily: fonts.sub, fontSize: 10, letterSpacing: 2, color: colors.sepia },
  scrollContent: { paddingBottom: 100 },
  hero: { alignItems: 'center', paddingVertical: 40, paddingHorizontal: 24 },
  header: { width: '100%', flexDirection: 'row', alignItems: 'center', marginBottom: 24, justifyContent: 'flex-start' },
  backBtn: { padding: 8, marginLeft: -8, marginRight: 12 },
  title: { fontFamily: fonts.display, fontSize: 32, color: colors.parchment, ...effects.textShadowDeep, flex: 1 },
  heroRuleTop: { width: 100, height: 2, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.sepia, marginBottom: 16, opacity: 0.5 },
  heroRuleBottom: { width: 100, height: 2, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.sepia, marginTop: 24, opacity: 0.5 },
  heroEyebrowRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
  heroEyebrow: { fontFamily: fonts.sub, fontSize: 9, letterSpacing: 4, color: colors.sepia },
  heroTitle: { fontFamily: fonts.display, fontSize: 32, color: colors.parchment, marginBottom: 4, ...effects.textShadowDeep },
  heroEst: { fontFamily: fonts.sub, fontSize: 8, letterSpacing: 3, color: colors.sepia, marginBottom: 16, opacity: 0.8 },
  heroDesc: { fontFamily: fonts.bodyItalic, fontSize: 13, color: colors.bone, textAlign: 'center', maxWidth: 260 },
  ornRule: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 24, paddingHorizontal: 40, opacity: 0.5 },
  ornLine: { flex: 1, height: 1, backgroundColor: colors.sepia },
  ornDiamond: { width: 6, height: 6, backgroundColor: colors.sepia, transform: [{ rotate: '45deg' }], marginHorizontal: 12 },
  legalActions: { flexDirection: 'column' },
  divider: { height: 1, backgroundColor: 'rgba(184,137,26,0.1)' },
  heritageFooter: { marginTop: 40, paddingHorizontal: 24, alignItems: 'center', paddingBottom: 40 },
  globalSaveBtn: { backgroundColor: 'transparent', borderWidth: 1, borderColor: colors.sepia, width: '100%', paddingVertical: 18, alignItems: 'center', borderRadius: 2, marginBottom: 32, ...effects.glowSepia },
  disabledBtn: { opacity: 0.5 },
  saveBtnContent: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  globalSaveBtnText: { fontFamily: fonts.sub, fontSize: 11, letterSpacing: 3, color: colors.sepia, fontWeight: '700' },
  legalFooter: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 24 },
  legalFooterLink: { fontFamily: fonts.sub, fontSize: 9, letterSpacing: 1.5, color: colors.fog, textDecorationLine: 'underline', textDecorationColor: colors.fog },
  footerDot: { width: 3, height: 3, borderRadius: 1.5, backgroundColor: colors.fog },
  memberSince: { fontFamily: fonts.sub, fontSize: 9, letterSpacing: 2, color: colors.parchment, marginBottom: 32 },
  endMarkRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 16 },
  endMarkLine: { width: 30, height: 1, backgroundColor: colors.sepia, opacity: 0.3 },
  heritageMark: { fontFamily: fonts.sub, fontSize: 9, letterSpacing: 2, color: colors.sepia, marginBottom: 8 },
  heritageCopyright: { fontFamily: fonts.bodyItalic, fontSize: 10, color: colors.fog },
  
  // Modal Styles
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.85)', justifyContent: 'center', alignItems: 'center', padding: 24 },
  modalContent: { backgroundColor: '#110D0A', borderWidth: 1, borderColor: '#30261A', borderRadius: 6, width: '100%', padding: 24 },
  modalHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 16 },
  modalTitle: { fontFamily: fonts.sub, fontSize: 11, letterSpacing: 2, color: colors.bloodReel },
  modalDesc: { fontFamily: fonts.body, fontSize: 13, color: colors.bone, lineHeight: 20, marginBottom: 24 },
  otpInput: { backgroundColor: colors.ink, borderWidth: 1, borderColor: '#30261A', color: colors.parchment, fontFamily: fonts.body, fontSize: 24, padding: 16, borderRadius: 4, textAlign: 'center', marginBottom: 32, letterSpacing: 8 },
  modalActions: { flexDirection: 'row', gap: 12 },
  modalBtnCancel: { flex: 1, paddingVertical: 14, backgroundColor: 'rgba(184,137,26,0.05)', borderRadius: 4, alignItems: 'center' },
  modalBtnCancelText: { fontFamily: fonts.sub, fontSize: 10, letterSpacing: 2, color: colors.fog },
  modalBtnConfirm: { flex: 1, paddingVertical: 14, backgroundColor: colors.bloodReel, borderRadius: 4, alignItems: 'center' },
  modalBtnConfirmText: { fontFamily: fonts.sub, fontSize: 10, letterSpacing: 2, color: colors.bone },
});
