-- ═══════════════════════════════════════════════════════════════════════════════
-- PROFILE-FREEZE-1 — NOT LIVE. This migration is intentionally a NO-OP.
-- ═══════════════════════════════════════════════════════════════════════════════
-- Audit ref: BACKEND-PROFILE-FREEZE-1 (HIGH in the repo; NOT PRESENT on live DB)
--
-- WAVE 0 (verified against the live DB 2026-06-26):
--   • `protect_profile_fields` DOES NOT EXIST on the live database.
--   • The only BEFORE triggers on public.profiles are set_profiles_updated_at,
--     tr_handle_privacy_switch, and tr_profiles_username_policy — none of which
--     revert role/tier/followers_count. There is NO profile-freeze on production.
--
-- The repo's 0002-era freeze trigger was never deployed to this database, so there
-- is nothing to fix. The original rewrite was removed to avoid creating an orphan
-- function and to avoid overwriting the live `protect_video_review_metrics` body
-- (which differs from the repo) with assumptions that don't match production.
--
-- If a profile-freeze trigger is ever introduced, re-derive the fix against the
-- THEN-current live function bodies. Until then: no action.
-- ═══════════════════════════════════════════════════════════════════════════════

-- (no-op)
