-- ═══════════════════════════════════════════════════════════════════════════════
-- PRIV-1 — NOT LIVE.  RL-1 — deferred.  This migration is intentionally a NO-OP.
-- ═══════════════════════════════════════════════════════════════════════════════
-- Audit refs: BACKEND-PRIV-1 (MEDIUM; NOT PRESENT on live DB), BACKEND-RL-1 (LOW)
--
-- WAVE 0 (verified against the live DB 2026-06-26):
--   • PRIV-1: `get_public_profile_analytics` DOES NOT EXIST on the live database,
--     so there is no private-analytics leak to gate. Nothing to fix.
--   • RL-1: `rate_limit_check` was not re-verified against the live schema. The
--     original fix here did CREATE OR REPLACE with the repo body, which would
--     overwrite a possibly-divergent live function. Deferred until the live body is
--     confirmed; it is only a search_path/qualification hardening (LOW), no live bug.
--
-- Both rewrites were removed so this file can't overwrite live functions with
-- repo assumptions. Re-derive against live bodies if/when these become relevant.
-- ═══════════════════════════════════════════════════════════════════════════════

-- (no-op)
