-- ═══════════════════════════════════════════════════════════════════════════════
-- COMP-SPOILER-1 (feed RPCs) — DEFERRED. This migration is intentionally a NO-OP.
-- ═══════════════════════════════════════════════════════════════════════════════
-- Audit ref: COMP-SPOILER-1 (LOW) — feed-veil portion only
--
-- The spoiler veil is fully live on every DIRECT-query surface (log detail, film
-- critiques, read-all, pulse) because those selects include is_spoiler. Only the
-- FEED preview can't veil yet, because the feed cursor RPCs don't return is_spoiler.
-- The client degrades gracefully (is_spoiler optional → no feed veil), so this is
-- non-blocking.
--
-- WAVE 0 / safety notes for when this is picked up:
--   • The live feed RPC bodies were NOT verified against the repo; do NOT blindly
--     CREATE OR REPLACE them (would clobber any live-only filtering).
--   • Adding a column to RETURNS TABLE CHANGES the return type, so a plain
--     CREATE OR REPLACE FAILS — it must be `DROP FUNCTION ...; CREATE FUNCTION ...`.
--   • Therefore: dump the live get_community_feed_auth_cursor /
--     get_following_feed_auth_cursor, add a trailing `is_spoiler boolean` +
--     `l.is_spoiler`, and DROP+CREATE — only after confirming the live body.
--
-- Removed the original body to prevent an accidental return-type-change failure /
-- clobber. No action until the live feed RPCs are dumped and matched.
-- ═══════════════════════════════════════════════════════════════════════════════

-- (no-op)
